// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocked_days.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBlockedDay = `-- name: CreateBlockedDay :one
INSERT INTO
  blocked_days (date, reason, business_id, professional_id)
VALUES
  ($1, $2, $3, $4)
RETURNING
  id, date, reason, business_id, professional_id, created_at, updated_at
`

type CreateBlockedDayParams struct {
	Date           pgtype.Timestamptz `json:"date"`
	Reason         string             `json:"reason"`
	BusinessID     pgtype.UUID        `json:"businessId"`
	ProfessionalID pgtype.UUID        `json:"professionalId"`
}

func (q *Queries) CreateBlockedDay(ctx context.Context, arg CreateBlockedDayParams) (BlockedDay, error) {
	row := q.db.QueryRow(ctx, createBlockedDay,
		arg.Date,
		arg.Reason,
		arg.BusinessID,
		arg.ProfessionalID,
	)
	var i BlockedDay
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Reason,
		&i.BusinessID,
		&i.ProfessionalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBlockedDay = `-- name: DeleteBlockedDay :execrows
DELETE FROM blocked_days
WHERE
  business_id = $1
  AND id = $2
`

type DeleteBlockedDayParams struct {
	BusinessID pgtype.UUID `json:"businessId"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteBlockedDay(ctx context.Context, arg DeleteBlockedDayParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBlockedDay, arg.BusinessID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBlockedDaysProfessionalID = `-- name: GetBlockedDaysProfessionalID :many
SELECT
  id,
  date,
  reason,
  business_id,
  professional_id,
  created_at,
  updated_at
FROM
  blocked_days
WHERE
  business_id = $1
  AND professional_id = $2
ORDER BY
  date DESC
`

type GetBlockedDaysProfessionalIDParams struct {
	BusinessID     pgtype.UUID `json:"businessId"`
	ProfessionalID pgtype.UUID `json:"professionalId"`
}

func (q *Queries) GetBlockedDaysProfessionalID(ctx context.Context, arg GetBlockedDaysProfessionalIDParams) ([]BlockedDay, error) {
	rows, err := q.db.Query(ctx, getBlockedDaysProfessionalID, arg.BusinessID, arg.ProfessionalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlockedDay
	for rows.Next() {
		var i BlockedDay
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Reason,
			&i.BusinessID,
			&i.ProfessionalID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlockedDay = `-- name: UpdateBlockedDay :execrows
UPDATE blocked_days
SET
  date = COALESCE($1, date),
  reason = COALESCE($2, reason),
  updated_at = now()
WHERE
  business_id = $3
  AND id = $4
`

type UpdateBlockedDayParams struct {
	Date       pgtype.Timestamptz `json:"date"`
	Reason     pgtype.Text        `json:"reason"`
	BusinessID pgtype.UUID        `json:"businessId"`
	ID         pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateBlockedDay(ctx context.Context, arg UpdateBlockedDayParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBlockedDay,
		arg.Date,
		arg.Reason,
		arg.BusinessID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
