// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocked_days.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBlockedDay = `-- name: CreateBlockedDay :one
INSERT INTO
  blocked_days (date, reason, business_id, professional_id)
VALUES
  ($1, $2, $3, $4)
RETURNING
  id, date, reason, business_id, professional_id, created_at, updated_at
`

type CreateBlockedDayParams struct {
	Date           pgtype.Timestamptz `json:"date"`
	Reason         string             `json:"reason"`
	BusinessID     pgtype.UUID        `json:"businessId"`
	ProfessionalID pgtype.UUID        `json:"professionalId"`
}

func (q *Queries) CreateBlockedDay(ctx context.Context, arg CreateBlockedDayParams) (BlockedDay, error) {
	row := q.db.QueryRow(ctx, createBlockedDay,
		arg.Date,
		arg.Reason,
		arg.BusinessID,
		arg.ProfessionalID,
	)
	var i BlockedDay
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Reason,
		&i.BusinessID,
		&i.ProfessionalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
