// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business_role_permissions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBusinessRoleOverrides = `-- name: DeleteBusinessRoleOverrides :execrows
DELETE FROM business_role_permissions
WHERE
  business_id = $1
  AND role_id = $2
`

type DeleteBusinessRoleOverridesParams struct {
	BusinessID pgtype.UUID `json:"businessId"`
	RoleID     pgtype.UUID `json:"roleId"`
}

func (q *Queries) DeleteBusinessRoleOverrides(ctx context.Context, arg DeleteBusinessRoleOverridesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBusinessRoleOverrides, arg.BusinessID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBusinessRolePermission = `-- name: DeleteBusinessRolePermission :execrows
DELETE FROM business_role_permissions
WHERE
  business_id = $1
  AND role_id = $2
  AND permission_id = $3
`

type DeleteBusinessRolePermissionParams struct {
	BusinessID   pgtype.UUID `json:"businessId"`
	RoleID       pgtype.UUID `json:"roleId"`
	PermissionID pgtype.UUID `json:"permissionId"`
}

func (q *Queries) DeleteBusinessRolePermission(ctx context.Context, arg DeleteBusinessRolePermissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBusinessRolePermission, arg.BusinessID, arg.RoleID, arg.PermissionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBusinessRoleOverrides = `-- name: GetBusinessRoleOverrides :many
SELECT
  brp.business_id,
  brp.role_id,
  brp.permission_id,
  brp.effect,
  p.action_key,
  p.name,
  p.category
FROM
  business_role_permissions brp
  JOIN permissions p ON p.id = brp.permission_id
WHERE
  brp.business_id = $1
  AND brp.role_id = $2
ORDER BY
  p.category ASC,
  p.action_key ASC
`

type GetBusinessRoleOverridesParams struct {
	BusinessID pgtype.UUID `json:"businessId"`
	RoleID     pgtype.UUID `json:"roleId"`
}

type GetBusinessRoleOverridesRow struct {
	BusinessID   pgtype.UUID `json:"businessId"`
	RoleID       pgtype.UUID `json:"roleId"`
	PermissionID pgtype.UUID `json:"permissionId"`
	Effect       string      `json:"effect"`
	ActionKey    string      `json:"actionKey"`
	Name         string      `json:"name"`
	Category     string      `json:"category"`
}

func (q *Queries) GetBusinessRoleOverrides(ctx context.Context, arg GetBusinessRoleOverridesParams) ([]GetBusinessRoleOverridesRow, error) {
	rows, err := q.db.Query(ctx, getBusinessRoleOverrides, arg.BusinessID, arg.RoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBusinessRoleOverridesRow
	for rows.Next() {
		var i GetBusinessRoleOverridesRow
		if err := rows.Scan(
			&i.BusinessID,
			&i.RoleID,
			&i.PermissionID,
			&i.Effect,
			&i.ActionKey,
			&i.Name,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasEffectivePermission = `-- name: HasEffectivePermission :one
SELECT
  EXISTS (
    SELECT
      1
    FROM
      permissions p
      LEFT JOIN role_permissions rp ON rp.permission_id = p.id
      AND rp.role_id = $2
      LEFT JOIN business_role_permissions brp ON brp.permission_id = p.id
      AND brp.role_id = $2
      AND brp.business_id = $1
    WHERE
      p.action_key = $3
      AND p.deleted_at IS NULL
      AND (
        brp.effect = 'grant'
        OR (
          rp.role_id IS NOT NULL
          AND (
            brp.effect IS NULL
            OR brp.effect <> 'deny'
          )
        )
      )
  ) AS has_permission
`

type HasEffectivePermissionParams struct {
	BusinessID pgtype.UUID `json:"businessId"`
	RoleID     pgtype.UUID `json:"roleId"`
	ActionKey  string      `json:"actionKey"`
}

func (q *Queries) HasEffectivePermission(ctx context.Context, arg HasEffectivePermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasEffectivePermission, arg.BusinessID, arg.RoleID, arg.ActionKey)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const listEffectivePermissions = `-- name: ListEffectivePermissions :many
SELECT
  p.id,
  p.name,
  p.category,
  p.action_key,
  p.description,
  (rp.role_id IS NOT NULL) AS in_baseline,
  brp.effect AS override_effect,
  (
    brp.effect = 'grant'
    OR (
      rp.role_id IS NOT NULL
      AND (
        brp.effect IS NULL
        OR brp.effect <> 'deny'
      )
    )
  ) AS is_effective
FROM
  permissions p
  LEFT JOIN role_permissions rp ON rp.permission_id = p.id
  AND rp.role_id = $2
  LEFT JOIN business_role_permissions brp ON brp.permission_id = p.id
  AND brp.role_id = $2
  AND brp.business_id = $1
WHERE
  p.deleted_at IS NULL
ORDER BY
  p.category ASC,
  p.action_key ASC
`

type ListEffectivePermissionsParams struct {
	BusinessID pgtype.UUID `json:"businessId"`
	RoleID     pgtype.UUID `json:"roleId"`
}

type ListEffectivePermissionsRow struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	Category       string      `json:"category"`
	ActionKey      string      `json:"actionKey"`
	Description    string      `json:"description"`
	InBaseline     interface{} `json:"inBaseline"`
	OverrideEffect pgtype.Text `json:"overrideEffect"`
	IsEffective    pgtype.Bool `json:"isEffective"`
}

func (q *Queries) ListEffectivePermissions(ctx context.Context, arg ListEffectivePermissionsParams) ([]ListEffectivePermissionsRow, error) {
	rows, err := q.db.Query(ctx, listEffectivePermissions, arg.BusinessID, arg.RoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEffectivePermissionsRow
	for rows.Next() {
		var i ListEffectivePermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.ActionKey,
			&i.Description,
			&i.InBaseline,
			&i.OverrideEffect,
			&i.IsEffective,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBusinessRolePermission = `-- name: UpsertBusinessRolePermission :one
INSERT INTO
  business_role_permissions (business_id, role_id, permission_id, effect)
VALUES
  ($1, $2, $3, $4)
ON CONFLICT (business_id, role_id, permission_id) DO UPDATE
SET
  effect = EXCLUDED.effect,
  updated_at = now()
RETURNING
  business_id, role_id, permission_id, effect, created_at, updated_at
`

type UpsertBusinessRolePermissionParams struct {
	BusinessID   pgtype.UUID `json:"businessId"`
	RoleID       pgtype.UUID `json:"roleId"`
	PermissionID pgtype.UUID `json:"permissionId"`
	Effect       string      `json:"effect"`
}

func (q *Queries) UpsertBusinessRolePermission(ctx context.Context, arg UpsertBusinessRolePermissionParams) (BusinessRolePermission, error) {
	row := q.db.QueryRow(ctx, upsertBusinessRolePermission,
		arg.BusinessID,
		arg.RoleID,
		arg.PermissionID,
		arg.Effect,
	)
	var i BusinessRolePermission
	err := row.Scan(
		&i.BusinessID,
		&i.RoleID,
		&i.PermissionID,
		&i.Effect,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
