// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: businesses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkSlugAvailability = `-- name: CheckSlugAvailability :one
SELECT
  EXISTS (
    SELECT
      1
    FROM
      businesses
    WHERE
      slug = $1
  ) AS slug_exists
`

func (q *Queries) CheckSlugAvailability(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, checkSlugAvailability, slug)
	var slug_exists bool
	err := row.Scan(&slug_exists)
	return slug_exists, err
}

const checkTaxIDAvailability = `-- name: CheckTaxIDAvailability :one
SELECT
  EXISTS (
    SELECT
      1
    FROM
      businesses
    WHERE
      tax_id = $1
  ) AS tax_id_exists
`

func (q *Queries) CheckTaxIDAvailability(ctx context.Context, taxID string) (bool, error) {
	row := q.db.QueryRow(ctx, checkTaxIDAvailability, taxID)
	var tax_id_exists bool
	err := row.Scan(&tax_id_exists)
	return tax_id_exists, err
}

const createBusiness = `-- name: CreateBusiness :one
INSERT INTO
  businesses (
    slug,
    tax_id,
    company_name,
    trade_name,
    description,
    street,
    city,
    province,
    country,
    zip_code,
    timezone,
    email,
    phone_number,
    whatsapp_number,
    website
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
  )
RETURNING
  id, slug, tax_id, company_name, trade_name, description, street, city, province, country, zip_code, timezone, email, phone_number, whatsapp_number, website, created_at, updated_at, deleted_at
`

type CreateBusinessParams struct {
	Slug           string      `json:"slug"`
	TaxID          string      `json:"taxId"`
	CompanyName    string      `json:"companyName"`
	TradeName      string      `json:"tradeName"`
	Description    string      `json:"description"`
	Street         string      `json:"street"`
	City           string      `json:"city"`
	Province       string      `json:"province"`
	Country        string      `json:"country"`
	ZipCode        string      `json:"zipCode"`
	Timezone       string      `json:"timezone"`
	Email          string      `json:"email"`
	PhoneNumber    string      `json:"phoneNumber"`
	WhatsappNumber pgtype.Text `json:"whatsappNumber"`
	Website        pgtype.Text `json:"website"`
}

func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, createBusiness,
		arg.Slug,
		arg.TaxID,
		arg.CompanyName,
		arg.TradeName,
		arg.Description,
		arg.Street,
		arg.City,
		arg.Province,
		arg.Country,
		arg.ZipCode,
		arg.Timezone,
		arg.Email,
		arg.PhoneNumber,
		arg.WhatsappNumber,
		arg.Website,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TaxID,
		&i.CompanyName,
		&i.TradeName,
		&i.Description,
		&i.Street,
		&i.City,
		&i.Province,
		&i.Country,
		&i.ZipCode,
		&i.Timezone,
		&i.Email,
		&i.PhoneNumber,
		&i.WhatsappNumber,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteBusiness = `-- name: DeleteBusiness :execrows
DELETE FROM businesses
WHERE
  id = $1
`

func (q *Queries) DeleteBusiness(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBusiness, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBusiness = `-- name: GetBusiness :one
SELECT
  id, slug, tax_id, company_name, trade_name, description, street, city, province, country, zip_code, timezone, email, phone_number, whatsapp_number, website, created_at, updated_at, deleted_at
FROM
  businesses
WHERE
  id = $1
`

func (q *Queries) GetBusiness(ctx context.Context, id pgtype.UUID) (Business, error) {
	row := q.db.QueryRow(ctx, getBusiness, id)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TaxID,
		&i.CompanyName,
		&i.TradeName,
		&i.Description,
		&i.Street,
		&i.City,
		&i.Province,
		&i.Country,
		&i.ZipCode,
		&i.Timezone,
		&i.Email,
		&i.PhoneNumber,
		&i.WhatsappNumber,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBusinessBySlug = `-- name: GetBusinessBySlug :one
SELECT
  id, slug, tax_id, company_name, trade_name, description, street, city, province, country, zip_code, timezone, email, phone_number, whatsapp_number, website, created_at, updated_at, deleted_at
FROM
  businesses
WHERE
  slug = $1
`

func (q *Queries) GetBusinessBySlug(ctx context.Context, slug string) (Business, error) {
	row := q.db.QueryRow(ctx, getBusinessBySlug, slug)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TaxID,
		&i.CompanyName,
		&i.TradeName,
		&i.Description,
		&i.Street,
		&i.City,
		&i.Province,
		&i.Country,
		&i.ZipCode,
		&i.Timezone,
		&i.Email,
		&i.PhoneNumber,
		&i.WhatsappNumber,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBusinesses = `-- name: GetBusinesses :many
SELECT
  id, slug, tax_id, company_name, trade_name, description, street, city, province, country, zip_code, timezone, email, phone_number, whatsapp_number, website, created_at, updated_at, deleted_at
FROM
  businesses
`

func (q *Queries) GetBusinesses(ctx context.Context) ([]Business, error) {
	rows, err := q.db.Query(ctx, getBusinesses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Business
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.TaxID,
			&i.CompanyName,
			&i.TradeName,
			&i.Description,
			&i.Street,
			&i.City,
			&i.Province,
			&i.Country,
			&i.ZipCode,
			&i.Timezone,
			&i.Email,
			&i.PhoneNumber,
			&i.WhatsappNumber,
			&i.Website,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBusiness = `-- name: UpdateBusiness :execrows
UPDATE businesses
SET
  slug = COALESCE($2, slug),
  tax_id = COALESCE($3, tax_id),
  company_name = COALESCE($4, company_name),
  trade_name = COALESCE($5, trade_name),
  description = COALESCE($6, description),
  street = COALESCE($7, street),
  city = COALESCE($8, city),
  province = COALESCE($9, province),
  country = COALESCE($10, country),
  zip_code = COALESCE($11, zip_code),
  timezone = COALESCE($12, timezone),
  email = COALESCE($13, email),
  phone_number = COALESCE($14, phone_number),
  whatsapp_number = COALESCE($15, whatsapp_number),
  website = COALESCE($16, website)
WHERE
  id = $1
`

type UpdateBusinessParams struct {
	ID             pgtype.UUID `json:"id"`
	Slug           pgtype.Text `json:"slug"`
	TaxID          pgtype.Text `json:"taxId"`
	CompanyName    pgtype.Text `json:"companyName"`
	TradeName      pgtype.Text `json:"tradeName"`
	Description    pgtype.Text `json:"description"`
	Street         pgtype.Text `json:"street"`
	City           pgtype.Text `json:"city"`
	Province       pgtype.Text `json:"province"`
	Country        pgtype.Text `json:"country"`
	ZipCode        pgtype.Text `json:"zipCode"`
	Timezone       pgtype.Text `json:"timezone"`
	Email          pgtype.Text `json:"email"`
	PhoneNumber    pgtype.Text `json:"phoneNumber"`
	WhatsappNumber pgtype.Text `json:"whatsappNumber"`
	Website        pgtype.Text `json:"website"`
}

func (q *Queries) UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBusiness,
		arg.ID,
		arg.Slug,
		arg.TaxID,
		arg.CompanyName,
		arg.TradeName,
		arg.Description,
		arg.Street,
		arg.City,
		arg.Province,
		arg.Country,
		arg.ZipCode,
		arg.Timezone,
		arg.Email,
		arg.PhoneNumber,
		arg.WhatsappNumber,
		arg.Website,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
