// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: businesses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBusiness = `-- name: CreateBusiness :one
INSERT INTO businesses (
   slug, tax_id, company_name, trade_name, description, street, city, province,
   country, zip_code, email, phone_number, whatsapp_number, website
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, slug, tax_id, company_name, trade_name, description, street, city, province, country, zip_code, email, phone_number, whatsapp_number, website, created_at, updated_at, deleted_at
`

type CreateBusinessParams struct {
	Slug           string      `json:"slug"`
	TaxID          string      `json:"taxId"`
	CompanyName    string      `json:"companyName"`
	TradeName      string      `json:"tradeName"`
	Description    string      `json:"description"`
	Street         string      `json:"street"`
	City           string      `json:"city"`
	Province       string      `json:"province"`
	Country        string      `json:"country"`
	ZipCode        string      `json:"zipCode"`
	Email          string      `json:"email"`
	PhoneNumber    string      `json:"phoneNumber"`
	WhatsappNumber pgtype.Text `json:"whatsappNumber"`
	Website        pgtype.Text `json:"website"`
}

func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, createBusiness,
		arg.Slug,
		arg.TaxID,
		arg.CompanyName,
		arg.TradeName,
		arg.Description,
		arg.Street,
		arg.City,
		arg.Province,
		arg.Country,
		arg.ZipCode,
		arg.Email,
		arg.PhoneNumber,
		arg.WhatsappNumber,
		arg.Website,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TaxID,
		&i.CompanyName,
		&i.TradeName,
		&i.Description,
		&i.Street,
		&i.City,
		&i.Province,
		&i.Country,
		&i.ZipCode,
		&i.Email,
		&i.PhoneNumber,
		&i.WhatsappNumber,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBusiness = `-- name: GetBusiness :one
SELECT id, slug, tax_id, company_name, trade_name, description, street, city, province, country, zip_code, email, phone_number, whatsapp_number, website, created_at, updated_at, deleted_at FROM businesses WHERE id = $1
`

func (q *Queries) GetBusiness(ctx context.Context, id pgtype.UUID) (Business, error) {
	row := q.db.QueryRow(ctx, getBusiness, id)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TaxID,
		&i.CompanyName,
		&i.TradeName,
		&i.Description,
		&i.Street,
		&i.City,
		&i.Province,
		&i.Country,
		&i.ZipCode,
		&i.Email,
		&i.PhoneNumber,
		&i.WhatsappNumber,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBusinesses = `-- name: GetBusinesses :many
SELECT id, slug, tax_id, company_name, trade_name, description, street, city, province, country, zip_code, email, phone_number, whatsapp_number, website, created_at, updated_at, deleted_at FROM businesses
`

func (q *Queries) GetBusinesses(ctx context.Context) ([]Business, error) {
	rows, err := q.db.Query(ctx, getBusinesses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Business
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.TaxID,
			&i.CompanyName,
			&i.TradeName,
			&i.Description,
			&i.Street,
			&i.City,
			&i.Province,
			&i.Country,
			&i.ZipCode,
			&i.Email,
			&i.PhoneNumber,
			&i.WhatsappNumber,
			&i.Website,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
