// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkRecurringEvents = `-- name: CheckRecurringEvents :many
SELECT
  id,
  business_id,
  professional_id,
  start_date
FROM
  events
WHERE
  business_id = $1
  AND professional_id = $2
  AND start_date >= $3
  AND start_date < ($3 + ($4 || ' days')::interval)
`

type CheckRecurringEventsParams struct {
	BusinessID     pgtype.UUID        `json:"businessId"`
	ProfessionalID pgtype.UUID        `json:"professionalId"`
	StartDate      pgtype.Timestamptz `json:"startDate"`
	Column4        pgtype.Text        `json:"column4"`
}

type CheckRecurringEventsRow struct {
	ID             pgtype.UUID        `json:"id"`
	BusinessID     pgtype.UUID        `json:"businessId"`
	ProfessionalID pgtype.UUID        `json:"professionalId"`
	StartDate      pgtype.Timestamptz `json:"startDate"`
}

func (q *Queries) CheckRecurringEvents(ctx context.Context, arg CheckRecurringEventsParams) ([]CheckRecurringEventsRow, error) {
	rows, err := q.db.Query(ctx, checkRecurringEvents,
		arg.BusinessID,
		arg.ProfessionalID,
		arg.StartDate,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CheckRecurringEventsRow
	for rows.Next() {
		var i CheckRecurringEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.ProfessionalID,
			&i.StartDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearRecurrentID = `-- name: ClearRecurrentID :execrows
UPDATE events
SET
  recurrent_id = NULL,
  updated_at = now()
WHERE
  business_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type ClearRecurrentIDParams struct {
	BusinessID pgtype.UUID `json:"businessId"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) ClearRecurrentID(ctx context.Context, arg ClearRecurrentIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearRecurrentID, arg.BusinessID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO
  events (
    title,
    start_date,
    end_date,
    business_id,
    professional_id,
    user_id,
    recurrent_id
  )
VALUES
  ($1, $2, $3, $4, $5, $6, $7)
RETURNING
  id, title, start_date, end_date, business_id, professional_id, user_id, status, recurrent_id, created_at, updated_at, deleted_at
`

type CreateEventParams struct {
	Title          string             `json:"title"`
	StartDate      pgtype.Timestamptz `json:"startDate"`
	EndDate        pgtype.Timestamptz `json:"endDate"`
	BusinessID     pgtype.UUID        `json:"businessId"`
	ProfessionalID pgtype.UUID        `json:"professionalId"`
	UserID         pgtype.UUID        `json:"userId"`
	RecurrentID    pgtype.UUID        `json:"recurrentId"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.BusinessID,
		arg.ProfessionalID,
		arg.UserID,
		arg.RecurrentID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.BusinessID,
		&i.ProfessionalID,
		&i.UserID,
		&i.Status,
		&i.RecurrentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :execrows
DELETE FROM events
WHERE
  business_id = $1
  AND id = $2
`

type DeleteEventParams struct {
	BusinessID pgtype.UUID `json:"businessId"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteEvent(ctx context.Context, arg DeleteEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEvent, arg.BusinessID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getByBusinessID = `-- name: GetByBusinessID :many
SELECT
  jsonb_build_object(
    'id',
    e.id,
    'title',
    e.title,
    'startDate',
    e.start_date,
    'endDate',
    e.end_date,
    'businessId',
    e.business_id,
    'userId',
    e.user_id,
    'status',
    e.status,
    'createdAt',
    e.created_at,
    'updatedAt',
    e.updated_at,
    'professional',
    jsonb_build_object(
      'id',
      p.id,
      'firstName',
      p.first_name,
      'lastName',
      p.last_name,
      'ic',
      p.ic,
      'professionalProfile',
      jsonb_build_object('professionalPrefix', pp.professional_prefix)
    ),
    'user',
    jsonb_build_object(
      'id',
      u.id,
      'firstName',
      u.first_name,
      'lastName',
      u.last_name,
      'email',
      u.email,
      'phoneNumber',
      u.phone_number,
      'ic',
      u.ic,
      'role',
      jsonb_build_object('name', ur.name, 'value', ur.value)
    )
  ) AS event
FROM
  events e
  LEFT JOIN users u ON u.id = e.user_id
  LEFT JOIN roles ur ON ur.id = u.role_id
  LEFT JOIN users p ON p.id = e.professional_id
  LEFT JOIN professional_profile pp ON pp.user_id = p.id
WHERE
  e.business_id = $1
  AND e.deleted_at IS NULL
ORDER BY
  e.start_date::date DESC,
  e.end_date::time DESC
LIMIT
  $2
`

type GetByBusinessIDParams struct {
	BusinessID pgtype.UUID `json:"businessId"`
	Limit      int32       `json:"limit"`
}

func (q *Queries) GetByBusinessID(ctx context.Context, arg GetByBusinessIDParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, getByBusinessID, arg.BusinessID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var event []byte
		if err := rows.Scan(&event); err != nil {
			return nil, err
		}
		items = append(items, event)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByBusinessProfessionalPatient = `-- name: GetByBusinessProfessionalPatient :many
SELECT
  jsonb_build_object(
    'id',
    e.id,
    'title',
    e.title,
    'startDate',
    e.start_date,
    'endDate',
    e.end_date,
    'businessId',
    e.business_id,
    'userId',
    e.user_id,
    'status',
    e.status,
    'createdAt',
    e.created_at,
    'updatedAt',
    e.updated_at,
    'professional',
    jsonb_build_object(
      'id',
      p.id,
      'firstName',
      p.first_name,
      'lastName',
      p.last_name,
      'ic',
      p.ic,
      'professionalProfile',
      jsonb_build_object('professionalPrefix', pp.professional_prefix)
    ),
    'user',
    jsonb_build_object(
      'id',
      u.id,
      'firstName',
      u.first_name,
      'lastName',
      u.last_name,
      'email',
      u.email,
      'phoneNumber',
      u.phone_number,
      'ic',
      u.ic,
      'role',
      jsonb_build_object('name', ur.name, 'value', ur.value)
    )
  ) AS event
FROM
  events e
  LEFT JOIN users u ON u.id = e.user_id
  LEFT JOIN roles ur ON ur.id = u.role_id
  LEFT JOIN users p ON p.id = e.professional_id
  LEFT JOIN professional_profile pp ON pp.user_id = p.id
WHERE
  e.business_id = $1
  AND e.professional_id = $2
  AND e.user_id = $3
  AND e.deleted_at IS NULL
ORDER BY
  e.start_date::date DESC,
  e.end_date::time DESC
`

type GetByBusinessProfessionalPatientParams struct {
	BusinessID     pgtype.UUID `json:"businessId"`
	ProfessionalID pgtype.UUID `json:"professionalId"`
	UserID         pgtype.UUID `json:"userId"`
}

func (q *Queries) GetByBusinessProfessionalPatient(ctx context.Context, arg GetByBusinessProfessionalPatientParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, getByBusinessProfessionalPatient, arg.BusinessID, arg.ProfessionalID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var event []byte
		if err := rows.Scan(&event); err != nil {
			return nil, err
		}
		items = append(items, event)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT
  jsonb_build_object(
    'id',
    e.id,
    'title',
    e.title,
    'startDate',
    e.start_date,
    'endDate',
    e.end_date,
    'businessId',
    e.business_id,
    'professionalId',
    e.professional_id,
    'userId',
    e.user_id,
    'status',
    e.status,
    'createdAt',
    e.created_at,
    'updatedAt',
    e.updated_at,
    'deletedAt',
    e.deleted_at,
    'professional',
    jsonb_build_object(
      'id',
      p.id,
      'ic',
      p.ic,
      'userName',
      p.user_name,
      'firstName',
      p.first_name,
      'lastName',
      p.last_name,
      'email',
      p.email,
      'password',
      p.password,
      'phoneNumber',
      p.phone_number,
      'roleId',
      p.role_id,
      'businessId',
      p.business_id,
      'refreshToken',
      p.refresh_token,
      'createdAt',
      p.created_at,
      'updatedAt',
      p.updated_at,
      'deletedAt',
      p.deleted_at,
      'professionalProfile',
      jsonb_build_object(
        'id',
        pp.id,
        'businessId',
        pp.business_id,
        'userId',
        pp.user_id,
        'licenseId',
        pp.license_id,
        'professionalPrefix',
        pp.professional_prefix,
        'specialty',
        pp.specialty,
        'workingDays',
        pp.working_days,
        'startHour',
        pp.start_hour,
        'endHour',
        pp.end_hour,
        'slotDuration',
        pp.slot_duration,
        'dailyExceptionStart',
        pp.daily_exception_start,
        'dailyExceptionEnd',
        pp.daily_exception_end,
        'createdAt',
        pp.created_at,
        'updatedAt',
        pp.updated_at,
        'deletedAt',
        pp.deleted_at
      )
    ),
    'user',
    jsonb_build_object(
      'id',
      u.id,
      'ic',
      u.ic,
      'userName',
      u.user_name,
      'firstName',
      u.first_name,
      'lastName',
      u.last_name,
      'email',
      u.email,
      'password',
      u.password,
      'phoneNumber',
      u.phone_number,
      'roleId',
      u.role_id,
      'businessId',
      u.business_id,
      'refreshToken',
      u.refresh_token,
      'createdAt',
      u.created_at,
      'updatedAt',
      u.updated_at,
      'deletedAt',
      u.deleted_at,
      'role',
      jsonb_build_object(
        'id',
        ur.id,
        'name',
        ur.name,
        'value',
        ur.value,
        'description',
        ur.description,
        'createdAt',
        ur.created_at,
        'updatedAt',
        ur.updated_at,
        'deletedAt',
        ur.deleted_at
      )
    )
  ) AS event
FROM
  events e
  LEFT JOIN users u ON u.id = e.user_id
  LEFT JOIN roles ur ON ur.id = u.role_id
  LEFT JOIN users p ON p.id = e.professional_id
  LEFT JOIN professional_profile pp ON pp.user_id = p.id
WHERE
  e.business_id = $1
  AND e.id = $2
  AND e.deleted_at IS NULL
`

type GetByIDParams struct {
	BusinessID pgtype.UUID `json:"businessId"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) GetByID(ctx context.Context, arg GetByIDParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getByID, arg.BusinessID, arg.ID)
	var event []byte
	err := row.Scan(&event)
	return event, err
}

const getByProfessionalDay = `-- name: GetByProfessionalDay :many
SELECT
  jsonb_build_object(
    'id',
    e.id,
    'title',
    e.title,
    'startDate',
    e.start_date,
    'endDate',
    e.end_date,
    'businessId',
    e.business_id,
    'professionalId',
    e.professional_id,
    'userId',
    e.user_id,
    'status',
    e.status,
    'createdAt',
    e.created_at,
    'updatedAt',
    e.updated_at,
    'professional',
    jsonb_build_object(
      'id',
      p.id,
      'firstName',
      p.first_name,
      'lastName',
      p.last_name,
      'ic',
      p.ic,
      'role',
      jsonb_build_object('name', pr.name, 'value', pr.value),
      'professionalProfile',
      jsonb_build_object('professionalPrefix', pp.professional_prefix)
    ),
    'user',
    jsonb_build_object(
      'id',
      u.id,
      'firstName',
      u.first_name,
      'lastName',
      u.last_name,
      'email',
      u.email,
      'phoneNumber',
      u.phone_number,
      'ic',
      u.ic,
      'role',
      jsonb_build_object('name', ur.name, 'value', ur.value)
    )
  ) AS event
FROM
  events e
  LEFT JOIN users u ON u.id = e.user_id
  LEFT JOIN roles ur ON ur.id = u.role_id
  LEFT JOIN users p ON p.id = e.professional_id
  LEFT JOIN roles pr ON pr.id = p.role_id
  LEFT JOIN professional_profile pp ON pp.user_id = p.id
WHERE
  e.business_id = $1
  AND e.professional_id = $2
  AND e.start_date >= $3
  AND e.start_date <= $4
  AND e.deleted_at IS NULL
ORDER BY
  e.start_date
`

type GetByProfessionalDayParams struct {
	BusinessID     pgtype.UUID        `json:"businessId"`
	ProfessionalID pgtype.UUID        `json:"professionalId"`
	StartDate      pgtype.Timestamptz `json:"startDate"`
	StartDate_2    pgtype.Timestamptz `json:"startDate2"`
}

func (q *Queries) GetByProfessionalDay(ctx context.Context, arg GetByProfessionalDayParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, getByProfessionalDay,
		arg.BusinessID,
		arg.ProfessionalID,
		arg.StartDate,
		arg.StartDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var event []byte
		if err := rows.Scan(&event); err != nil {
			return nil, err
		}
		items = append(items, event)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByProfessionalDayArray = `-- name: GetByProfessionalDayArray :many
SELECT
  e.start_date
FROM
  events e
WHERE
  e.business_id = $1
  AND e.professional_id = $2
  AND e.start_date >= $3
  AND e.start_date <= $4
  AND e.deleted_at IS NULL
ORDER BY
  e.start_date
`

type GetByProfessionalDayArrayParams struct {
	BusinessID     pgtype.UUID        `json:"businessId"`
	ProfessionalID pgtype.UUID        `json:"professionalId"`
	StartDate      pgtype.Timestamptz `json:"startDate"`
	StartDate_2    pgtype.Timestamptz `json:"startDate2"`
}

func (q *Queries) GetByProfessionalDayArray(ctx context.Context, arg GetByProfessionalDayArrayParams) ([]pgtype.Timestamptz, error) {
	rows, err := q.db.Query(ctx, getByProfessionalDayArray,
		arg.BusinessID,
		arg.ProfessionalID,
		arg.StartDate,
		arg.StartDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Timestamptz
	for rows.Next() {
		var start_date pgtype.Timestamptz
		if err := rows.Scan(&start_date); err != nil {
			return nil, err
		}
		items = append(items, start_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDaysWithEvents = `-- name: GetDaysWithEvents :many
SELECT DISTINCT
  DATE (start_date) AS day
FROM
  events
WHERE
  business_id = $1
  AND professional_id = $2
  AND start_date >= $3
  AND start_date <= $4
ORDER BY
  day
`

type GetDaysWithEventsParams struct {
	BusinessID     pgtype.UUID        `json:"businessId"`
	ProfessionalID pgtype.UUID        `json:"professionalId"`
	StartDate      pgtype.Timestamptz `json:"startDate"`
	StartDate_2    pgtype.Timestamptz `json:"startDate2"`
}

func (q *Queries) GetDaysWithEvents(ctx context.Context, arg GetDaysWithEventsParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, getDaysWithEvents,
		arg.BusinessID,
		arg.ProfessionalID,
		arg.StartDate,
		arg.StartDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var day pgtype.Date
		if err := rows.Scan(&day); err != nil {
			return nil, err
		}
		items = append(items, day)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventRecurrentID = `-- name: GetEventRecurrentID :one
SELECT
  recurrent_id
FROM
  events
WHERE
  business_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type GetEventRecurrentIDParams struct {
	BusinessID pgtype.UUID `json:"businessId"`
	ID         pgtype.UUID `json:"id"`
}

// / Recurrent event queries / --
func (q *Queries) GetEventRecurrentID(ctx context.Context, arg GetEventRecurrentIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getEventRecurrentID, arg.BusinessID, arg.ID)
	var recurrent_id pgtype.UUID
	err := row.Scan(&recurrent_id)
	return recurrent_id, err
}

const getEventsByProfessionalID = `-- name: GetEventsByProfessionalID :many
SELECT
  jsonb_build_object(
    'id',
    e.id,
    'title',
    e.title,
    'startDate',
    e.start_date,
    'endDate',
    e.end_date,
    'businessId',
    e.business_id,
    'professionalId',
    e.professional_id,
    'userId',
    e.user_id,
    'recurrentId',
    e.recurrent_id,
    'status',
    e.status,
    'createdAt',
    e.created_at,
    'updatedAt',
    e.updated_at,
    'professional',
    jsonb_build_object(
      'id',
      p.id,
      'firstName',
      p.first_name,
      'lastName',
      p.last_name,
      'ic',
      p.ic,
      'role',
      jsonb_build_object('name', pr.name, 'value', pr.value),
      'professionalProfile',
      jsonb_build_object('professionalPrefix', pp.professional_prefix)
    ),
    'user',
    jsonb_build_object(
      'id',
      u.id,
      'firstName',
      u.first_name,
      'lastName',
      u.last_name,
      'email',
      u.email,
      'phoneNumber',
      u.phone_number,
      'ic',
      u.ic,
      'role',
      jsonb_build_object('name', ur.name, 'value', ur.value)
    ),
    'siblings',
    (
      SELECT
        COALESCE(
          jsonb_agg(
            jsonb_build_object(
              'id',
              s.id,
              'startDate',
              s.start_date,
              'endDate',
              s.end_date,
              'status',
              s.status
            )
            ORDER BY
              s.start_date ASC
          ),
          '[]'::jsonb
        )
      FROM
        events s
      WHERE
        s.recurrent_id = e.recurrent_id
        AND s.recurrent_id IS NOT NULL
        AND s.deleted_at IS NULL
    )
  ) AS event
FROM
  events e
  LEFT JOIN users u ON u.id = e.user_id
  LEFT JOIN roles ur ON ur.id = u.role_id
  LEFT JOIN users p ON p.id = e.professional_id
  LEFT JOIN roles pr ON pr.id = p.role_id
  LEFT JOIN professional_profile pp ON pp.user_id = p.id
WHERE
  e.business_id = $1
  AND e.professional_id = $2
  AND e.deleted_at IS NULL
  AND (
    $3::timestamptz IS NULL
    OR e.end_date >= $3
  )
  AND (
    $4::timestamptz IS NULL
    OR e.start_date <= $4
  )
ORDER BY
  e.start_date
`

type GetEventsByProfessionalIDParams struct {
	BusinessID     pgtype.UUID        `json:"businessId"`
	ProfessionalID pgtype.UUID        `json:"professionalId"`
	StartDate      pgtype.Timestamptz `json:"startDate"`
	EndDate        pgtype.Timestamptz `json:"endDate"`
}

func (q *Queries) GetEventsByProfessionalID(ctx context.Context, arg GetEventsByProfessionalIDParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, getEventsByProfessionalID,
		arg.BusinessID,
		arg.ProfessionalID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var event []byte
		if err := rows.Scan(&event); err != nil {
			return nil, err
		}
		items = append(items, event)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsFiltered = `-- name: GetEventsFiltered :many
SELECT
  jsonb_build_object(
    'id',
    e.id,
    'title',
    e.title,
    'startDate',
    e.start_date,
    'endDate',
    e.end_date,
    'businessId',
    e.business_id,
    'userId',
    e.user_id,
    'recurrentId',
    e.recurrent_id,
    'status',
    e.status,
    'createdAt',
    e.created_at,
    'updatedAt',
    e.created_at,
    'user',
    jsonb_build_object(
      'id',
      u.id,
      'ic',
      u.ic,
      'firstName',
      u.first_name,
      'lastName',
      u.last_name,
      'email',
      u.email,
      'phoneNumber',
      u.phone_number,
      'role',
      jsonb_build_object('name', r.name, 'value', r.value)
    ),
    'professional',
    jsonb_build_object(
      'id',
      p.id,
      'firstName',
      p.first_name,
      'lastName',
      p.last_name,
      'ic',
      p.ic,
      'professionalProfile',
      jsonb_build_object('professionalPrefix', pp.professional_prefix)
    ),
    'siblings',
    (
      SELECT
        COALESCE(
          jsonb_agg(
            jsonb_build_object(
              'id',
              s.id,
              'startDate',
              s.start_date,
              'endDate',
              s.end_date,
              'status',
              s.status
            )
            ORDER BY
              s.start_date ASC
          ),
          '[]'::jsonb
        )
      FROM
        events s
      WHERE
        s.recurrent_id = e.recurrent_id
        AND s.recurrent_id IS NOT NULL
        AND s.deleted_at IS NULL
    )
  ) AS event
FROM
  events e
  LEFT JOIN users u ON e.user_id = u.id
  LEFT JOIN roles r ON u.role_id = r.id
  LEFT JOIN users p ON e.professional_id = p.id
  LEFT JOIN professional_profile pp ON p.id = pp.user_id
WHERE
  e.business_id = $1
  AND (
    $2::timestamp IS NULL
    OR e.start_date >= $2
  )
  AND (
    $3::timestamp IS NULL
    OR e.start_date <= $3
  )
  AND (
    $4::uuid IS NULL
    OR u.id = $4
  )
  AND (
    $5::uuid IS NULL
    OR p.id = $5
  )
  AND (
    $6::text IS NULL
    OR e.status::text = $6
  )
  AND (
    $7::text IS NULL
    OR (
      $7::text = 'true'
      AND e.recurrent_id IS NOT NULL
    )
    OR (
      $7::text = 'false'
      AND e.recurrent_id IS NULL
    )
  )
ORDER BY
  CASE
    WHEN $8 = 'start_date'
    AND $9 = 'asc' THEN e.start_date
  END ASC,
  CASE
    WHEN $8 = 'start_date'
    AND $9 = 'desc' THEN e.start_date
  END DESC,
  CASE
    WHEN $8 = 'status'
    AND $9 = 'asc' THEN e.status
  END ASC,
  CASE
    WHEN $8 = 'status'
    AND $9 = 'desc' THEN e.status
  END DESC,
  CASE
    WHEN $8 = 'title'
    AND $9 = 'asc' THEN e.title
  END ASC,
  CASE
    WHEN $8 = 'title'
    AND $9 = 'desc' THEN e.title
  END DESC,
  CASE
    WHEN $8 = 'professional.firstName'
    AND $9 = 'asc' THEN p.first_name
  END ASC,
  CASE
    WHEN $8 = 'professional.firstName'
    AND $9 = 'desc' THEN p.first_name
  END DESC,
  CASE
    WHEN $8 = 'user.firstName'
    AND $9 = 'asc' THEN u.first_name
  END ASC,
  CASE
    WHEN $8 = 'user.firstName'
    AND $9 = 'desc' THEN u.first_name
  END DESC,
  e.start_date::date DESC,
  e.start_date::time ASC
LIMIT
  $11
OFFSET
  $10
`

type GetEventsFilteredParams struct {
	BusinessID     pgtype.UUID      `json:"businessId"`
	StartOfDay     pgtype.Timestamp `json:"startOfDay"`
	EndOfDay       pgtype.Timestamp `json:"endOfDay"`
	PatientID      pgtype.UUID      `json:"patientId"`
	ProfessionalID pgtype.UUID      `json:"professionalId"`
	Status         pgtype.Text      `json:"status"`
	Recurrent      pgtype.Text      `json:"recurrent"`
	SortBy         interface{}      `json:"sortBy"`
	SortOrder      interface{}      `json:"sortOrder"`
	QueryOffset    int32            `json:"queryOffset"`
	QueryLimit     int32            `json:"queryLimit"`
}

func (q *Queries) GetEventsFiltered(ctx context.Context, arg GetEventsFilteredParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, getEventsFiltered,
		arg.BusinessID,
		arg.StartOfDay,
		arg.EndOfDay,
		arg.PatientID,
		arg.ProfessionalID,
		arg.Status,
		arg.Recurrent,
		arg.SortBy,
		arg.SortOrder,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var event []byte
		if err := rows.Scan(&event); err != nil {
			return nil, err
		}
		items = append(items, event)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilteredCount = `-- name: GetFilteredCount :one
SELECT
  COUNT(e.id)::int AS total
FROM
  events e
  LEFT JOIN users u ON e.user_id = u.id
  LEFT JOIN users p ON e.professional_id = p.id
WHERE
  e.business_id = $1
  AND (
    $2::timestamp IS NULL
    OR e.start_date >= $2
  )
  AND (
    $3::timestamp IS NULL
    OR e.start_date <= $3
  )
  AND (
    $4::uuid IS NULL
    OR u.id = $4
  )
  AND (
    $5::uuid IS NULL
    OR p.id = $5
  )
  AND (
    $6::text IS NULL
    OR e.status::text = $6
  )
  AND (
    $7::text IS NULL
    OR (
      $7::text = 'true'
      AND e.recurrent_id IS NOT NULL
    )
    OR (
      $7::text = 'false'
      AND e.recurrent_id IS NULL
    )
  )
`

type GetFilteredCountParams struct {
	BusinessID     pgtype.UUID      `json:"businessId"`
	StartOfDay     pgtype.Timestamp `json:"startOfDay"`
	EndOfDay       pgtype.Timestamp `json:"endOfDay"`
	PatientID      pgtype.UUID      `json:"patientId"`
	ProfessionalID pgtype.UUID      `json:"professionalId"`
	Status         pgtype.Text      `json:"status"`
	Recurrent      pgtype.Text      `json:"recurrent"`
}

func (q *Queries) GetFilteredCount(ctx context.Context, arg GetFilteredCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, getFilteredCount,
		arg.BusinessID,
		arg.StartOfDay,
		arg.EndOfDay,
		arg.PatientID,
		arg.ProfessionalID,
		arg.Status,
		arg.Recurrent,
	)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const getIDsByRecurrentID = `-- name: GetIDsByRecurrentID :many
SELECT
  id
FROM
  events
WHERE
  recurrent_id = $1
  AND business_id = $2
  AND deleted_at IS NULL
`

type GetIDsByRecurrentIDParams struct {
	RecurrentID pgtype.UUID `json:"recurrentId"`
	BusinessID  pgtype.UUID `json:"businessId"`
}

func (q *Queries) GetIDsByRecurrentID(ctx context.Context, arg GetIDsByRecurrentIDParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getIDsByRecurrentID, arg.RecurrentID, arg.BusinessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET
  title = COALESCE($3, title),
  start_date = COALESCE($4, start_date),
  end_date = COALESCE($5, end_date),
  professional_id = COALESCE($6, professional_id),
  user_id = COALESCE($7, user_id),
  status = COALESCE($8, status),
  recurrent_id = COALESCE($9, recurrent_id),
  updated_at = now()
WHERE
  business_id = $1
  AND id = $2
  AND deleted_at IS NULL
RETURNING
  id,
  title,
  start_date,
  end_date,
  business_id,
  professional_id,
  user_id,
  recurrent_id,
  status,
  created_at,
  updated_at,
  deleted_at
`

type UpdateEventParams struct {
	BusinessID     pgtype.UUID        `json:"businessId"`
	ID             pgtype.UUID        `json:"id"`
	Title          pgtype.Text        `json:"title"`
	StartDate      pgtype.Timestamptz `json:"startDate"`
	EndDate        pgtype.Timestamptz `json:"endDate"`
	ProfessionalID pgtype.UUID        `json:"professionalId"`
	UserID         pgtype.UUID        `json:"userId"`
	Status         NullEventStatus    `json:"status"`
	RecurrentID    pgtype.UUID        `json:"recurrentId"`
}

type UpdateEventRow struct {
	ID             pgtype.UUID        `json:"id"`
	Title          string             `json:"title"`
	StartDate      pgtype.Timestamptz `json:"startDate"`
	EndDate        pgtype.Timestamptz `json:"endDate"`
	BusinessID     pgtype.UUID        `json:"businessId"`
	ProfessionalID pgtype.UUID        `json:"professionalId"`
	UserID         pgtype.UUID        `json:"userId"`
	RecurrentID    pgtype.UUID        `json:"recurrentId"`
	Status         EventStatus        `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt      pgtype.Timestamptz `json:"deletedAt"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (UpdateEventRow, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.BusinessID,
		arg.ID,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.ProfessionalID,
		arg.UserID,
		arg.Status,
		arg.RecurrentID,
	)
	var i UpdateEventRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.BusinessID,
		&i.ProfessionalID,
		&i.UserID,
		&i.RecurrentID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateStatus = `-- name: UpdateStatus :execrows
UPDATE events
SET
  status = $3,
  updated_at = now()
WHERE
  business_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type UpdateStatusParams struct {
	BusinessID pgtype.UUID `json:"businessId"`
	ID         pgtype.UUID `json:"id"`
	Status     EventStatus `json:"status"`
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStatus, arg.BusinessID, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
