// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO
  events (
    title,
    start_date,
    end_date,
    professional_id,
    user_id
  )
VALUES
  ($1, $2, $3, $4, $5)
RETURNING
  id, title, start_date, end_date, business_id, professional_id, user_id, status, created_at, updated_at, deleted_at
`

type CreateEventParams struct {
	Title          string             `json:"title"`
	StartDate      pgtype.Timestamptz `json:"startDate"`
	EndDate        pgtype.Timestamptz `json:"endDate"`
	ProfessionalID pgtype.UUID        `json:"professionalId"`
	UserID         pgtype.UUID        `json:"userId"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.ProfessionalID,
		arg.UserID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.BusinessID,
		&i.ProfessionalID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEventsByProfessionalID = `-- name: GetEventsByProfessionalID :many
SELECT
  id, title, start_date, end_date, business_id, professional_id, user_id, status, created_at, updated_at, deleted_at
FROM
  events
WHERE
  id = $1
`

func (q *Queries) GetEventsByProfessionalID(ctx context.Context, id pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByProfessionalID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.BusinessID,
			&i.ProfessionalID,
			&i.UserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
