// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: medical_histories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMedicalHistory = `-- name: CreateMedicalHistory :one
INSERT INTO
  medical_histories (
    business_id,
    user_id,
    professional_id,
    event_id,
    date,
    reason,
    recipe,
    comments
  )
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING
  id, business_id, user_id, professional_id, event_id, date, reason, recipe, comments, created_at, updated_at, deleted_at
`

type CreateMedicalHistoryParams struct {
	BusinessID     pgtype.UUID        `json:"businessId"`
	UserID         pgtype.UUID        `json:"userId"`
	ProfessionalID pgtype.UUID        `json:"professionalId"`
	EventID        pgtype.UUID        `json:"eventId"`
	Date           pgtype.Timestamptz `json:"date"`
	Reason         string             `json:"reason"`
	Recipe         bool               `json:"recipe"`
	Comments       string             `json:"comments"`
}

func (q *Queries) CreateMedicalHistory(ctx context.Context, arg CreateMedicalHistoryParams) (MedicalHistory, error) {
	row := q.db.QueryRow(ctx, createMedicalHistory,
		arg.BusinessID,
		arg.UserID,
		arg.ProfessionalID,
		arg.EventID,
		arg.Date,
		arg.Reason,
		arg.Recipe,
		arg.Comments,
	)
	var i MedicalHistory
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.ProfessionalID,
		&i.EventID,
		&i.Date,
		&i.Reason,
		&i.Recipe,
		&i.Comments,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
