// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type EventStatus string

const (
	EventStatusAbsent     EventStatus = "absent"
	EventStatusCancelled  EventStatus = "cancelled"
	EventStatusInProgress EventStatus = "in_progress"
	EventStatusPending    EventStatus = "pending"
	EventStatusPresent    EventStatus = "present"
)

func (e *EventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventStatus(s)
	case string:
		*e = EventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EventStatus: %T", src)
	}
	return nil
}

type NullEventStatus struct {
	EventStatus EventStatus `json:"eventStatus"`
	Valid       bool        `json:"valid"` // Valid is true if EventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventStatus), nil
}

type Business struct {
	ID             pgtype.UUID        `json:"id"`
	Slug           string             `json:"slug"`
	TaxID          string             `json:"taxId"`
	CompanyName    string             `json:"companyName"`
	TradeName      string             `json:"tradeName"`
	Description    string             `json:"description"`
	Street         string             `json:"street"`
	City           string             `json:"city"`
	Province       string             `json:"province"`
	Country        string             `json:"country"`
	ZipCode        string             `json:"zipCode"`
	Email          string             `json:"email"`
	PhoneNumber    string             `json:"phoneNumber"`
	WhatsappNumber pgtype.Text        `json:"whatsappNumber"`
	Website        pgtype.Text        `json:"website"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt      pgtype.Timestamptz `json:"deletedAt"`
}

type Event struct {
	ID             pgtype.UUID        `json:"id"`
	Title          string             `json:"title"`
	StartDate      pgtype.Timestamptz `json:"startDate"`
	EndDate        pgtype.Timestamptz `json:"endDate"`
	BusinessID     pgtype.UUID        `json:"businessId"`
	ProfessionalID pgtype.UUID        `json:"professionalId"`
	UserID         pgtype.UUID        `json:"userId"`
	Status         EventStatus        `json:"status"`
	RecurrentID    pgtype.UUID        `json:"recurrentId"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt      pgtype.Timestamptz `json:"deletedAt"`
}

type MedicalHistory struct {
	ID             pgtype.UUID        `json:"id"`
	BusinessID     pgtype.UUID        `json:"businessId"`
	UserID         pgtype.UUID        `json:"userId"`
	ProfessionalID pgtype.UUID        `json:"professionalId"`
	EventID        pgtype.UUID        `json:"eventId"`
	Date           pgtype.Timestamptz `json:"date"`
	Reason         string             `json:"reason"`
	Recipe         bool               `json:"recipe"`
	Comments       string             `json:"comments"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt      pgtype.Timestamptz `json:"deletedAt"`
}

type PatientProfile struct {
	ID                    pgtype.UUID        `json:"id"`
	BusinessID            pgtype.UUID        `json:"businessId"`
	UserID                pgtype.UUID        `json:"userId"`
	Gender                string             `json:"gender"`
	BirthDay              pgtype.Date        `json:"birthDay"`
	BloodType             string             `json:"bloodType"`
	Weight                pgtype.Numeric     `json:"weight"`
	Height                pgtype.Numeric     `json:"height"`
	EmergencyContactName  string             `json:"emergencyContactName"`
	EmergencyContactPhone string             `json:"emergencyContactPhone"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt             pgtype.Timestamptz `json:"deletedAt"`
}

type Permission struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Category    string             `json:"category"`
	ActionKey   string             `json:"actionKey"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt   pgtype.Timestamptz `json:"deletedAt"`
}

type ProfessionalProfile struct {
	ID                  pgtype.UUID        `json:"id"`
	BusinessID          pgtype.UUID        `json:"businessId"`
	UserID              pgtype.UUID        `json:"userId"`
	LicenseID           string             `json:"licenseId"`
	ProfessionalPrefix  string             `json:"professionalPrefix"`
	Specialty           string             `json:"specialty"`
	WorkingDays         string             `json:"workingDays"`
	StartHour           string             `json:"startHour"`
	EndHour             string             `json:"endHour"`
	SlotDuration        string             `json:"slotDuration"`
	DailyExceptionStart pgtype.Text        `json:"dailyExceptionStart"`
	DailyExceptionEnd   pgtype.Text        `json:"dailyExceptionEnd"`
	CreatedAt           pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt           pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt           pgtype.Timestamptz `json:"deletedAt"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Value       string             `json:"value"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt   pgtype.Timestamptz `json:"deletedAt"`
}

type RolePermission struct {
	RoleID       pgtype.UUID        `json:"roleId"`
	PermissionID pgtype.UUID        `json:"permissionId"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

type Setting struct {
	ID        pgtype.UUID        `json:"id"`
	Module    string             `json:"module"`
	Submodule pgtype.Text        `json:"submodule"`
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Ic           string             `json:"ic"`
	UserName     string             `json:"userName"`
	FirstName    string             `json:"firstName"`
	LastName     string             `json:"lastName"`
	Email        string             `json:"email"`
	Password     string             `json:"password"`
	PhoneNumber  string             `json:"phoneNumber"`
	RoleID       pgtype.UUID        `json:"roleId"`
	BusinessID   pgtype.UUID        `json:"businessId"`
	RefreshToken pgtype.Text        `json:"refreshToken"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt    pgtype.Timestamptz `json:"deletedAt"`
}
