// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patient_profile.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPatientProfile = `-- name: CreatePatientProfile :one
INSERT INTO patient_profile (
    business_id, user_id, gender, birth_day, blood_type,
    weight, height, emergency_contact_name, emergency_contact_phone
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, business_id, user_id, gender, birth_day, blood_type, weight, height, emergency_contact_name, emergency_contact_phone, created_at, updated_at, deleted_at
`

type CreatePatientProfileParams struct {
	BusinessID            pgtype.UUID    `json:"businessId"`
	UserID                pgtype.UUID    `json:"userId"`
	Gender                string         `json:"gender"`
	BirthDay              pgtype.Date    `json:"birthDay"`
	BloodType             string         `json:"bloodType"`
	Weight                pgtype.Numeric `json:"weight"`
	Height                pgtype.Numeric `json:"height"`
	EmergencyContactName  string         `json:"emergencyContactName"`
	EmergencyContactPhone string         `json:"emergencyContactPhone"`
}

func (q *Queries) CreatePatientProfile(ctx context.Context, arg CreatePatientProfileParams) (PatientProfile, error) {
	row := q.db.QueryRow(ctx, createPatientProfile,
		arg.BusinessID,
		arg.UserID,
		arg.Gender,
		arg.BirthDay,
		arg.BloodType,
		arg.Weight,
		arg.Height,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
	)
	var i PatientProfile
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.Gender,
		&i.BirthDay,
		&i.BloodType,
		&i.Weight,
		&i.Height,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
