// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (
    name, category, action_key, description
) VALUES (
    $1, $2, $3, $4
) RETURNING id, name, category, action_key, description, created_at, updated_at, deleted_at
`

type CreatePermissionParams struct {
	Name        string `json:"name"`
	Category    string `json:"category"`
	ActionKey   string `json:"actionKey"`
	Description string `json:"description"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission,
		arg.Name,
		arg.Category,
		arg.ActionKey,
		arg.Description,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.ActionKey,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions WHERE id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePermission, id)
	return err
}

const getPermission = `-- name: GetPermission :one
SELECT id, name, category, action_key, description, created_at, updated_at, deleted_at FROM permissions WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPermission(ctx context.Context, id pgtype.UUID) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermission, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.ActionKey,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPermissions = `-- name: GetPermissions :many
SELECT id, name, category, action_key, description, created_at, updated_at, deleted_at FROM permissions WHERE deleted_at IS NULL
`

func (q *Queries) GetPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.ActionKey,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionsWithSoftDeleted = `-- name: GetPermissionsWithSoftDeleted :many
SELECT id, name, category, action_key, description, created_at, updated_at, deleted_at FROM permissions
`

func (q *Queries) GetPermissionsWithSoftDeleted(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getPermissionsWithSoftDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.ActionKey,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restorePermission = `-- name: RestorePermission :one
UPDATE permissions SET deleted_at = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
RETURNING id, name, category, action_key, description, created_at, updated_at, deleted_at
`

func (q *Queries) RestorePermission(ctx context.Context, id pgtype.UUID) (Permission, error) {
	row := q.db.QueryRow(ctx, restorePermission, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.ActionKey,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeletePermission = `-- name: SoftDeletePermission :one
UPDATE permissions SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, category, action_key, description, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeletePermission(ctx context.Context, id pgtype.UUID) (Permission, error) {
	row := q.db.QueryRow(ctx, softDeletePermission, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.ActionKey,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePermission = `-- name: UpdatePermission :one
UPDATE permissions SET
  name = COALESCE($2, name),
  category = COALESCE($3, category),
  action_key = COALESCE($4, action_key),
  description = COALESCE($5, description),
  updated_at = now()
WHERE id = $1
RETURNING id, name, category, action_key, description, created_at, updated_at, deleted_at
`

type UpdatePermissionParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        pgtype.Text `json:"name"`
	Category    pgtype.Text `json:"category"`
	ActionKey   pgtype.Text `json:"actionKey"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, updatePermission,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.ActionKey,
		arg.Description,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.ActionKey,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
