// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: professional_profile.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfessionalProfile = `-- name: CreateProfessionalProfile :one
INSERT INTO
  professional_profile (
    business_id,
    user_id,
    license_id,
    professional_prefix,
    specialty,
    working_days,
    start_hour,
    end_hour,
    slot_duration,
    daily_exception_start,
    daily_exception_end
  )
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING
  id, business_id, user_id, license_id, professional_prefix, specialty, working_days, start_hour, end_hour, slot_duration, daily_exception_start, daily_exception_end, created_at, updated_at, deleted_at
`

type CreateProfessionalProfileParams struct {
	BusinessID          pgtype.UUID `json:"businessId"`
	UserID              pgtype.UUID `json:"userId"`
	LicenseID           string      `json:"licenseId"`
	ProfessionalPrefix  string      `json:"professionalPrefix"`
	Specialty           string      `json:"specialty"`
	WorkingDays         string      `json:"workingDays"`
	StartHour           string      `json:"startHour"`
	EndHour             string      `json:"endHour"`
	SlotDuration        string      `json:"slotDuration"`
	DailyExceptionStart pgtype.Text `json:"dailyExceptionStart"`
	DailyExceptionEnd   pgtype.Text `json:"dailyExceptionEnd"`
}

func (q *Queries) CreateProfessionalProfile(ctx context.Context, arg CreateProfessionalProfileParams) (ProfessionalProfile, error) {
	row := q.db.QueryRow(ctx, createProfessionalProfile,
		arg.BusinessID,
		arg.UserID,
		arg.LicenseID,
		arg.ProfessionalPrefix,
		arg.Specialty,
		arg.WorkingDays,
		arg.StartHour,
		arg.EndHour,
		arg.SlotDuration,
		arg.DailyExceptionStart,
		arg.DailyExceptionEnd,
	)
	var i ProfessionalProfile
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.LicenseID,
		&i.ProfessionalPrefix,
		&i.Specialty,
		&i.WorkingDays,
		&i.StartHour,
		&i.EndHour,
		&i.SlotDuration,
		&i.DailyExceptionStart,
		&i.DailyExceptionEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProfessionalProfileByUserID = `-- name: GetProfessionalProfileByUserID :one
SELECT
  id, business_id, user_id, license_id, professional_prefix, specialty, working_days, start_hour, end_hour, slot_duration, daily_exception_start, daily_exception_end, created_at, updated_at, deleted_at
FROM
  professional_profile
WHERE
  business_id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type GetProfessionalProfileByUserIDParams struct {
	BusinessID pgtype.UUID `json:"businessId"`
	UserID     pgtype.UUID `json:"userId"`
}

func (q *Queries) GetProfessionalProfileByUserID(ctx context.Context, arg GetProfessionalProfileByUserIDParams) (ProfessionalProfile, error) {
	row := q.db.QueryRow(ctx, getProfessionalProfileByUserID, arg.BusinessID, arg.UserID)
	var i ProfessionalProfile
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.LicenseID,
		&i.ProfessionalPrefix,
		&i.Specialty,
		&i.WorkingDays,
		&i.StartHour,
		&i.EndHour,
		&i.SlotDuration,
		&i.DailyExceptionStart,
		&i.DailyExceptionEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
