// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (
    name, value, description
)
VALUES (
    $1, $2, $3
)
RETURNING id, name, value, description, created_at, updated_at, deleted_at
`

type CreateRoleParams struct {
	Name        string `json:"name"`
	Value       string `json:"value"`
	Description string `json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Value, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM roles
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteRole(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRole = `-- name: GetRole :one
SELECT id, name, value, description, created_at, updated_at, deleted_at FROM roles
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetRole(ctx context.Context, id pgtype.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRoleWithSoftDeleted = `-- name: GetRoleWithSoftDeleted :one
SELECT id, name, value, description, created_at, updated_at, deleted_at FROM roles
WHERE id = $1
`

func (q *Queries) GetRoleWithSoftDeleted(ctx context.Context, id pgtype.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleWithSoftDeleted, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRoles = `-- name: GetRoles :many
SELECT id, name, value, description, created_at, updated_at, deleted_at FROM roles
WHERE deleted_at IS NULL
ORDER BY value ASC
`

func (q *Queries) GetRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, getRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Value,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolesWithSoftDeleted = `-- name: GetRolesWithSoftDeleted :many
SELECT id, name, value, description, created_at, updated_at, deleted_at FROM roles
ORDER BY value ASC
`

func (q *Queries) GetRolesWithSoftDeleted(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, getRolesWithSoftDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Value,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreRole = `-- name: RestoreRole :one
UPDATE roles SET deleted_at = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
RETURNING id, name, value, description, created_at, updated_at, deleted_at
`

func (q *Queries) RestoreRole(ctx context.Context, id pgtype.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, restoreRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteRole = `-- name: SoftDeleteRole :one
UPDATE roles SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, value, description, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteRole(ctx context.Context, id pgtype.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, softDeleteRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles SET
    name = COALESCE($2, name),
    value = COALESCE($3, value),
    description = COALESCE($4, description),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, value, description, created_at, updated_at, deleted_at
`

type UpdateRoleParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        pgtype.Text `json:"name"`
	Value       pgtype.Text `json:"value"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.ID,
		arg.Name,
		arg.Value,
		arg.Description,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
