// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role_permissions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRolePermission = `-- name: CreateRolePermission :one
INSERT INTO role_permissions (
    role_id, permission_id
)
VALUES (
    $1, $2
)
RETURNING role_id, permission_id, created_at, updated_at
`

type CreateRolePermissionParams struct {
	RoleID       pgtype.UUID `json:"roleId"`
	PermissionID pgtype.UUID `json:"permissionId"`
}

func (q *Queries) CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) (RolePermission, error) {
	row := q.db.QueryRow(ctx, createRolePermission, arg.RoleID, arg.PermissionID)
	var i RolePermission
	err := row.Scan(
		&i.RoleID,
		&i.PermissionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
