// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role_permissions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRolePermission = `-- name: CreateRolePermission :one
INSERT INTO role_permissions (
    role_id, permission_id
)
VALUES (
    $1, $2
)
RETURNING role_id, permission_id, created_at, updated_at
`

type CreateRolePermissionParams struct {
	RoleID       pgtype.UUID `json:"roleId"`
	PermissionID pgtype.UUID `json:"permissionId"`
}

func (q *Queries) CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) (RolePermission, error) {
	row := q.db.QueryRow(ctx, createRolePermission, arg.RoleID, arg.PermissionID)
	var i RolePermission
	err := row.Scan(
		&i.RoleID,
		&i.PermissionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRolePermissionsByRoleID = `-- name: DeleteRolePermissionsByRoleID :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissionsByRoleID(ctx context.Context, roleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolePermissionsByRoleID, roleID)
	return err
}

const hasPermission = `-- name: HasPermission :one
SELECT EXISTS (
    SELECT 1 FROM role_permissions rp
    JOIN permissions p ON p.id = rp.permission_id
    WHERE rp.role_id = $1 AND p.action_key = $2
) AS has_permission
`

type HasPermissionParams struct {
	RoleID    pgtype.UUID `json:"roleId"`
	ActionKey string      `json:"actionKey"`
}

func (q *Queries) HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPermission, arg.RoleID, arg.ActionKey)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}
