// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (
    name, value, description
)
VALUES (
    $1, $2, $3
)
RETURNING id, name, value, description, created_at, updated_at, deleted_at
`

type CreateRoleParams struct {
	Name        string `json:"name"`
	Value       string `json:"value"`
	Description string `json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Value, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM roles
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteRole(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRoleWithPermissions = `-- name: GetRoleWithPermissions :many
SELECT
   r.id, r.name, r.value, r.description, r.created_at, r.updated_at, r.deleted_at,
   rp.role_id, rp.permission_id, rp.created_at AS rp_created_at, rp.updated_at AS rp_updated_at,
   p.id AS p_id, p.name AS p_name, p.category AS p_category, p.action_key AS p_action_key,
   p.description AS p_description, p.created_at AS p_created_at, p.updated_at AS p_updated_at,
   p.deleted_at AS p_deleted_at
FROM roles r
LEFT JOIN role_permissions rp ON rp.role_id = r.id
LEFT JOIN permissions p ON p.id = rp.permission_id
WHERE r.id = $1 AND r.deleted_at IS NULL
`

type GetRoleWithPermissionsRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Value        string             `json:"value"`
	Description  string             `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt    pgtype.Timestamptz `json:"deletedAt"`
	RoleID       pgtype.UUID        `json:"roleId"`
	PermissionID pgtype.UUID        `json:"permissionId"`
	RpCreatedAt  pgtype.Timestamptz `json:"rpCreatedAt"`
	RpUpdatedAt  pgtype.Timestamptz `json:"rpUpdatedAt"`
	PID          pgtype.UUID        `json:"pId"`
	PName        pgtype.Text        `json:"pName"`
	PCategory    pgtype.Text        `json:"pCategory"`
	PActionKey   pgtype.Text        `json:"pActionKey"`
	PDescription pgtype.Text        `json:"pDescription"`
	PCreatedAt   pgtype.Timestamptz `json:"pCreatedAt"`
	PUpdatedAt   pgtype.Timestamptz `json:"pUpdatedAt"`
	PDeletedAt   pgtype.Timestamptz `json:"pDeletedAt"`
}

func (q *Queries) GetRoleWithPermissions(ctx context.Context, id pgtype.UUID) ([]GetRoleWithPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getRoleWithPermissions, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoleWithPermissionsRow
	for rows.Next() {
		var i GetRoleWithPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Value,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RoleID,
			&i.PermissionID,
			&i.RpCreatedAt,
			&i.RpUpdatedAt,
			&i.PID,
			&i.PName,
			&i.PCategory,
			&i.PActionKey,
			&i.PDescription,
			&i.PCreatedAt,
			&i.PUpdatedAt,
			&i.PDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleWithSoftDeleted = `-- name: GetRoleWithSoftDeleted :one
SELECT id, name, value, description, created_at, updated_at, deleted_at FROM roles
WHERE id = $1
`

func (q *Queries) GetRoleWithSoftDeleted(ctx context.Context, id pgtype.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleWithSoftDeleted, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRoles = `-- name: GetRoles :many
SELECT id, name, value, description, created_at, updated_at, deleted_at FROM roles
WHERE deleted_at IS NULL
ORDER BY value ASC
`

func (q *Queries) GetRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, getRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Value,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolesWithSoftDeleted = `-- name: GetRolesWithSoftDeleted :many
SELECT id, name, value, description, created_at, updated_at, deleted_at FROM roles
ORDER BY value ASC
`

func (q *Queries) GetRolesWithSoftDeleted(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, getRolesWithSoftDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Value,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreRole = `-- name: RestoreRole :one
UPDATE roles SET deleted_at = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
RETURNING id, name, value, description, created_at, updated_at, deleted_at
`

func (q *Queries) RestoreRole(ctx context.Context, id pgtype.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, restoreRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteRole = `-- name: SoftDeleteRole :one
UPDATE roles SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, value, description, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteRole(ctx context.Context, id pgtype.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, softDeleteRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles SET
    name = COALESCE($2, name),
    value = COALESCE($3, value),
    description = COALESCE($4, description),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, value, description, created_at, updated_at, deleted_at
`

type UpdateRoleParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        pgtype.Text `json:"name"`
	Value       pgtype.Text `json:"value"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.ID,
		arg.Name,
		arg.Value,
		arg.Description,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
