// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSettingsByModule = `-- name: GetSettingsByModule :many
SELECT
  id, module, submodule, key, value, title, created_at, updated_at
FROM
  settings
WHERE
  module = $1
`

func (q *Queries) GetSettingsByModule(ctx context.Context, module string) ([]Setting, error) {
	rows, err := q.db.Query(ctx, getSettingsByModule, module)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.Submodule,
			&i.Key,
			&i.Value,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSetting = `-- name: UpdateSetting :execrows
UPDATE settings
SET
  module = COALESCE($2, module),
  submodule = COALESCE($3, submodule),
  key = COALESCE($4, key),
  value = COALESCE($5, value),
  title = COALESCE($6, title),
  updated_at = now()
WHERE
  id = $1
`

type UpdateSettingParams struct {
	ID        pgtype.UUID `json:"id"`
	Module    pgtype.Text `json:"module"`
	Submodule pgtype.Text `json:"submodule"`
	Key       pgtype.Text `json:"key"`
	Value     pgtype.Text `json:"value"`
	Title     pgtype.Text `json:"title"`
}

func (q *Queries) UpdateSetting(ctx context.Context, arg UpdateSettingParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSetting,
		arg.ID,
		arg.Module,
		arg.Submodule,
		arg.Key,
		arg.Value,
		arg.Title,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
