// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearRefreshToken = `-- name: ClearRefreshToken :one
UPDATE users
SET refresh_token = NULL, updated_at = now()
WHERE id = $1
RETURNING id, ic, user_name, first_name, last_name, email, password, phone_number, role_id, business_id, refresh_token, created_at, updated_at, deleted_at
`

func (q *Queries) ClearRefreshToken(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, clearRefreshToken, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Ic,
		&i.UserName,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.RoleID,
		&i.BusinessID,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    ic, user_name, first_name, last_name,
    email, password, phone_number,
    role_id, business_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, ic, user_name, first_name, last_name, email, password, phone_number, role_id, business_id, refresh_token, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Ic          string      `json:"ic"`
	UserName    string      `json:"userName"`
	FirstName   string      `json:"firstName"`
	LastName    string      `json:"lastName"`
	Email       string      `json:"email"`
	Password    string      `json:"password"`
	PhoneNumber string      `json:"phoneNumber"`
	RoleID      pgtype.UUID `json:"roleId"`
	BusinessID  pgtype.UUID `json:"businessId"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Ic,
		arg.UserName,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.PhoneNumber,
		arg.RoleID,
		arg.BusinessID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Ic,
		&i.UserName,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.RoleID,
		&i.BusinessID,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getMe = `-- name: GetMe :many
SELECT
    "user"."id",
    "user"."ic",
    "user"."user_name",
    "user"."first_name",
    "user"."last_name",
    "user"."email",
    "user"."phone_number",
    "user"."role_id",
    "user"."business_id",
    "user"."refresh_token",
    "user"."created_at",
    "user"."updated_at",
    "user"."deleted_at",
    "role"."id"          AS "role_id",
    "role"."name"        AS "role_name",
    "role"."value"       AS "role_value",
    "rp"."role_id"       AS "rp_role_id",
    "rp"."permission_id" AS "rp_permission_id",
    "p"."id"             AS "permission_id",
    "p"."action_key"     AS "permission_action_key"
FROM users "user"
LEFT JOIN roles "role"
    ON "role"."id" = "user"."role_id"
LEFT JOIN role_permissions "rp"
    ON "rp"."role_id" = "role"."id"
LEFT JOIN permissions "p"
    ON "p"."id" = "rp"."permission_id"
WHERE "user"."business_id" = $1 AND "user"."id" = $2
`

type GetMeParams struct {
	BusinessID pgtype.UUID `json:"businessId"`
	ID         pgtype.UUID `json:"id"`
}

type GetMeRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Ic                  string             `json:"ic"`
	UserName            string             `json:"userName"`
	FirstName           string             `json:"firstName"`
	LastName            string             `json:"lastName"`
	Email               string             `json:"email"`
	PhoneNumber         string             `json:"phoneNumber"`
	RoleID              pgtype.UUID        `json:"roleId"`
	BusinessID          pgtype.UUID        `json:"businessId"`
	RefreshToken        pgtype.Text        `json:"refreshToken"`
	CreatedAt           pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt           pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt           pgtype.Timestamptz `json:"deletedAt"`
	RoleID_2            pgtype.UUID        `json:"roleId2"`
	RoleName            pgtype.Text        `json:"roleName"`
	RoleValue           pgtype.Text        `json:"roleValue"`
	RpRoleID            pgtype.UUID        `json:"rpRoleId"`
	RpPermissionID      pgtype.UUID        `json:"rpPermissionId"`
	PermissionID        pgtype.UUID        `json:"permissionId"`
	PermissionActionKey pgtype.Text        `json:"permissionActionKey"`
}

func (q *Queries) GetMe(ctx context.Context, arg GetMeParams) ([]GetMeRow, error) {
	rows, err := q.db.Query(ctx, getMe, arg.BusinessID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMeRow
	for rows.Next() {
		var i GetMeRow
		if err := rows.Scan(
			&i.ID,
			&i.Ic,
			&i.UserName,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PhoneNumber,
			&i.RoleID,
			&i.BusinessID,
			&i.RefreshToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RoleID_2,
			&i.RoleName,
			&i.RoleValue,
			&i.RpRoleID,
			&i.RpPermissionID,
			&i.PermissionID,
			&i.PermissionActionKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, ic, user_name, first_name, last_name, email, password, phone_number, role_id, business_id, refresh_token, created_at, updated_at, deleted_at FROM users
WHERE business_id = $1 AND email = $2 AND deleted_at IS NULL
`

type GetUserByEmailParams struct {
	BusinessID pgtype.UUID `json:"businessId"`
	Email      string      `json:"email"`
}

// AUTH
func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.BusinessID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Ic,
		&i.UserName,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.RoleID,
		&i.BusinessID,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, ic, user_name, first_name, last_name, email, password, phone_number, role_id, business_id, refresh_token, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Ic,
		&i.UserName,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.RoleID,
		&i.BusinessID,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByIDWithSoftDeleted = `-- name: GetUserByIDWithSoftDeleted :one
SELECT
    "user"."id",
    "user"."ic",
    "user"."user_name",
    "user"."first_name",
    "user"."last_name",
    "user"."email",
    "user"."phone_number",
    "user"."business_id",
    "user"."created_at",
    "user"."updated_at",
    "user"."deleted_at",
    "role"."id"          AS "role_id",
    "role"."name"        AS "role_name",
    "role"."value"       AS "role_value",
    "role"."description" AS "role_description"
FROM users "user"
LEFT JOIN roles "role"
    ON "role"."id" = "user"."role_id"
WHERE "user"."business_id" = $1 AND "user"."id" = $2
`

type GetUserByIDWithSoftDeletedParams struct {
	BusinessID pgtype.UUID `json:"businessId"`
	ID         pgtype.UUID `json:"id"`
}

type GetUserByIDWithSoftDeletedRow struct {
	ID              pgtype.UUID        `json:"id"`
	Ic              string             `json:"ic"`
	UserName        string             `json:"userName"`
	FirstName       string             `json:"firstName"`
	LastName        string             `json:"lastName"`
	Email           string             `json:"email"`
	PhoneNumber     string             `json:"phoneNumber"`
	BusinessID      pgtype.UUID        `json:"businessId"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt       pgtype.Timestamptz `json:"deletedAt"`
	RoleID          pgtype.UUID        `json:"roleId"`
	RoleName        pgtype.Text        `json:"roleName"`
	RoleValue       pgtype.Text        `json:"roleValue"`
	RoleDescription pgtype.Text        `json:"roleDescription"`
}

func (q *Queries) GetUserByIDWithSoftDeleted(ctx context.Context, arg GetUserByIDWithSoftDeletedParams) (GetUserByIDWithSoftDeletedRow, error) {
	row := q.db.QueryRow(ctx, getUserByIDWithSoftDeleted, arg.BusinessID, arg.ID)
	var i GetUserByIDWithSoftDeletedRow
	err := row.Scan(
		&i.ID,
		&i.Ic,
		&i.UserName,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.BusinessID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RoleID,
		&i.RoleName,
		&i.RoleValue,
		&i.RoleDescription,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, ic, user_name, first_name, last_name, email, password, phone_number, role_id, business_id, refresh_token, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NULL
ORDER BY last_name ASC
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Ic,
			&i.UserName,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Password,
			&i.PhoneNumber,
			&i.RoleID,
			&i.BusinessID,
			&i.RefreshToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByRole = `-- name: GetUsersByRole :many
SELECT
    "user"."id",
    "user"."ic",
    "user"."user_name",
    "user"."first_name",
    "user"."last_name",
    "user"."email",
    "user"."phone_number",
    "user"."business_id",
    "user"."created_at",
    "user"."updated_at",
    "user"."deleted_at",
    "role"."id"          AS "role_id",
    "role"."name"        AS "role_name",
    "role"."value"       AS "role_value",
    "role"."description" AS "role_description"
FROM users "user"
LEFT JOIN roles "role"
    ON "role"."id" = "user"."role_id"
WHERE "user"."business_id" = $1 AND "role"."value" = $2 AND "user"."deleted_at" IS NULL
`

type GetUsersByRoleParams struct {
	BusinessID pgtype.UUID `json:"businessId"`
	Value      string      `json:"value"`
}

type GetUsersByRoleRow struct {
	ID              pgtype.UUID        `json:"id"`
	Ic              string             `json:"ic"`
	UserName        string             `json:"userName"`
	FirstName       string             `json:"firstName"`
	LastName        string             `json:"lastName"`
	Email           string             `json:"email"`
	PhoneNumber     string             `json:"phoneNumber"`
	BusinessID      pgtype.UUID        `json:"businessId"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt       pgtype.Timestamptz `json:"deletedAt"`
	RoleID          pgtype.UUID        `json:"roleId"`
	RoleName        pgtype.Text        `json:"roleName"`
	RoleValue       pgtype.Text        `json:"roleValue"`
	RoleDescription pgtype.Text        `json:"roleDescription"`
}

func (q *Queries) GetUsersByRole(ctx context.Context, arg GetUsersByRoleParams) ([]GetUsersByRoleRow, error) {
	rows, err := q.db.Query(ctx, getUsersByRole, arg.BusinessID, arg.Value)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByRoleRow
	for rows.Next() {
		var i GetUsersByRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Ic,
			&i.UserName,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PhoneNumber,
			&i.BusinessID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RoleID,
			&i.RoleName,
			&i.RoleValue,
			&i.RoleDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByRoleWithSoftDeleted = `-- name: GetUsersByRoleWithSoftDeleted :many
SELECT
    "user"."id",
    "user"."ic",
    "user"."user_name",
    "user"."first_name",
    "user"."last_name",
    "user"."email",
    "user"."phone_number",
    "user"."business_id",
    "user"."created_at",
    "user"."updated_at",
    "user"."deleted_at",
    "role"."id"          AS "role_id",
    "role"."name"        AS "role_name",
    "role"."value"       AS "role_value",
    "role"."description" AS "role_description"
FROM users "user"
LEFT JOIN roles "role"
    ON "role"."id" = "user"."role_id"
WHERE "user"."business_id" = $1 AND "role"."value" = $2
`

type GetUsersByRoleWithSoftDeletedParams struct {
	BusinessID pgtype.UUID `json:"businessId"`
	Value      string      `json:"value"`
}

type GetUsersByRoleWithSoftDeletedRow struct {
	ID              pgtype.UUID        `json:"id"`
	Ic              string             `json:"ic"`
	UserName        string             `json:"userName"`
	FirstName       string             `json:"firstName"`
	LastName        string             `json:"lastName"`
	Email           string             `json:"email"`
	PhoneNumber     string             `json:"phoneNumber"`
	BusinessID      pgtype.UUID        `json:"businessId"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt       pgtype.Timestamptz `json:"deletedAt"`
	RoleID          pgtype.UUID        `json:"roleId"`
	RoleName        pgtype.Text        `json:"roleName"`
	RoleValue       pgtype.Text        `json:"roleValue"`
	RoleDescription pgtype.Text        `json:"roleDescription"`
}

func (q *Queries) GetUsersByRoleWithSoftDeleted(ctx context.Context, arg GetUsersByRoleWithSoftDeletedParams) ([]GetUsersByRoleWithSoftDeletedRow, error) {
	rows, err := q.db.Query(ctx, getUsersByRoleWithSoftDeleted, arg.BusinessID, arg.Value)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByRoleWithSoftDeletedRow
	for rows.Next() {
		var i GetUsersByRoleWithSoftDeletedRow
		if err := rows.Scan(
			&i.ID,
			&i.Ic,
			&i.UserName,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PhoneNumber,
			&i.BusinessID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RoleID,
			&i.RoleName,
			&i.RoleValue,
			&i.RoleDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersWithSoftDeleted = `-- name: GetUsersWithSoftDeleted :many
SELECT id, ic, user_name, first_name, last_name, email, password, phone_number, role_id, business_id, refresh_token, created_at, updated_at, deleted_at FROM users
ORDER BY last_name ASC
`

func (q *Queries) GetUsersWithSoftDeleted(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersWithSoftDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Ic,
			&i.UserName,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Password,
			&i.PhoneNumber,
			&i.RoleID,
			&i.BusinessID,
			&i.RefreshToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreUser = `-- name: RestoreUser :execrows
UPDATE users
SET deleted_at = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
RETURNING id, ic, user_name, first_name, last_name, email, password, phone_number, role_id, business_id, refresh_token, created_at, updated_at, deleted_at
`

func (q *Queries) RestoreUser(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, restoreUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE users
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, ic, user_name, first_name, last_name, email, password, phone_number, role_id, business_id, refresh_token, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRefreshToken = `-- name: UpdateRefreshToken :one
UPDATE users
SET refresh_token = $2, updated_at = now()
WHERE id = $1
RETURNING id, ic, user_name, first_name, last_name, email, password, phone_number, role_id, business_id, refresh_token, created_at, updated_at, deleted_at
`

type UpdateRefreshTokenParams struct {
	ID           pgtype.UUID `json:"id"`
	RefreshToken pgtype.Text `json:"refreshToken"`
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) (User, error) {
	row := q.db.QueryRow(ctx, updateRefreshToken, arg.ID, arg.RefreshToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Ic,
		&i.UserName,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.RoleID,
		&i.BusinessID,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET ic = $2, user_name = $3, first_name = $4, last_name = $5,
    email = $6, password = $7, phone_number = $8, role_id = $9,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, ic, user_name, first_name, last_name, email, password, phone_number, role_id, business_id, refresh_token, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID          pgtype.UUID `json:"id"`
	Ic          string      `json:"ic"`
	UserName    string      `json:"userName"`
	FirstName   string      `json:"firstName"`
	LastName    string      `json:"lastName"`
	Email       string      `json:"email"`
	Password    string      `json:"password"`
	PhoneNumber string      `json:"phoneNumber"`
	RoleID      pgtype.UUID `json:"roleId"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Ic,
		arg.UserName,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.PhoneNumber,
		arg.RoleID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Ic,
		&i.UserName,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.RoleID,
		&i.BusinessID,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
